
export const metadata = {
    title: 'About us',
    description: 'Generated by create next app',
}

export default function Page() {
    return <main>
        <h1>Hello, About us Page!</h1>
    </main>
  }