import 'bootstrap/dist/css/bootstrap.css';
import './globals.css'
import { Inter, Asap, Poppins } from 'next/font/google'
import BootstrapClient from './components/BootstrapClient'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })
const asap = Asap({ subsets: ['latin'], display: 'swap', weight:['100', '700'] })
const poppins = Poppins({ subsets: ['latin'], display: 'swap', weight: '400'})

export const metadata = {
  title: 'Empuls3',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <BootstrapClient />
      </body>
    </html>
  )
}